/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.yono_ms.model.models

import io.github.yono_ms.model.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param fullName 
 * @param `private` 
 * @param htmlUrl 
 * @param description 
 * @param stargazersCount 
 * @param forksCount 
 * @param language 
 * @param owner 
 */
@Serializable

data class Repository (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "full_name")
    val fullName: kotlin.String? = null,

    @SerialName(value = "private")
    val `private`: kotlin.Boolean? = null,

    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "stargazers_count")
    val stargazersCount: kotlin.Int? = null,

    @SerialName(value = "forks_count")
    val forksCount: kotlin.Int? = null,

    @SerialName(value = "language")
    val language: kotlin.String? = null,

    @SerialName(value = "owner")
    val owner: User? = null

)

