/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.yono_ms.model.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.github.yono_ms.model.models.Repository
import io.github.yono_ms.model.models.User

class RepositoryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Repository
        //val modelInstance = Repository()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `fullName`
        should("test fullName") {
            // uncomment below to test the property
            //modelInstance.fullName shouldBe ("TODO")
        }

        // to test the property ``private``
        should("test `private`") {
            // uncomment below to test the property
            //modelInstance.`private` shouldBe ("TODO")
        }

        // to test the property `htmlUrl`
        should("test htmlUrl") {
            // uncomment below to test the property
            //modelInstance.htmlUrl shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `stargazersCount`
        should("test stargazersCount") {
            // uncomment below to test the property
            //modelInstance.stargazersCount shouldBe ("TODO")
        }

        // to test the property `forksCount`
        should("test forksCount") {
            // uncomment below to test the property
            //modelInstance.forksCount shouldBe ("TODO")
        }

        // to test the property `language`
        should("test language") {
            // uncomment below to test the property
            //modelInstance.language shouldBe ("TODO")
        }

        // to test the property `owner`
        should("test owner") {
            // uncomment below to test the property
            //modelInstance.owner shouldBe ("TODO")
        }

    }
}
