/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.github.yono_ms.model.models

import io.github.yono_ms.model.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param fullName 
 * @param `private` 
 * @param htmlUrl 
 * @param description 
 * @param stargazersCount 
 * @param forksCount 
 * @param language 
 * @param owner 
 * @param updatedAt 
 */
@Serializable

data class Repository (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "full_name")
    val fullName: kotlin.String,

    @SerialName(value = "private")
    val `private`: kotlin.Boolean,

    @Contextual @SerialName(value = "html_url")
    val htmlUrl: java.net.URI,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "stargazers_count")
    val stargazersCount: kotlin.Int,

    @SerialName(value = "forks_count")
    val forksCount: kotlin.Int,

    @SerialName(value = "language")
    val language: kotlin.String,

    @SerialName(value = "owner")
    val owner: User,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

